# Generated by Django 6.0.3 on 2026-04-06 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('provider_type', models.CharField(choices=[('exchange', 'Exchange'), ('otc', 'OTC'), ('wallet', 'Wallet'), ('node', 'Node'), ('other', 'Other')], db_index=True, default='exchange', max_length=32, verbose_name='Тип провайдера')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, verbose_name='Приоритет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('supports_market_snapshot', models.BooleanField(default=True, verbose_name='Поддерживает market snapshot')),
                ('supports_asset_metadata', models.BooleanField(default=False, verbose_name='Поддерживает asset metadata')),
                ('supports_network_metadata', models.BooleanField(default=False, verbose_name='Поддерживает network metadata')),
                ('supports_rest', models.BooleanField(default=True, verbose_name='Поддерживает REST')),
                ('supports_ws', models.BooleanField(default=False, verbose_name='Поддерживает WebSocket')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capability', to='app_providers.provider', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Provider capability',
                'verbose_name_plural': 'Provider capabilities',
            },
        ),
        migrations.CreateModel(
            name='ProviderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance'), ('error', 'Error')], db_index=True, default='active', max_length=32, verbose_name='Статус')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный sync')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя ошибка')),
                ('last_error_message', models.TextField(blank=True, verbose_name='Текст последней ошибки')),
                ('health_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Health score')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_record', to='app_providers.provider', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Provider status',
                'verbose_name_plural': 'Provider statuses',
            },
        ),
        migrations.CreateModel(
            name='ProviderEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('endpoint_type', models.CharField(choices=[('tickers', 'Tickers'), ('currencies', 'Currencies'), ('networks', 'Networks'), ('metadata', 'Metadata'), ('other', 'Other')], db_index=True, max_length=32, verbose_name='Тип endpoint')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=8, verbose_name='HTTP метод')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, verbose_name='Таймаут, сек')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='app_providers.provider', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Provider endpoint',
                'verbose_name_plural': 'Provider endpoints',
                'indexes': [models.Index(fields=['provider', 'endpoint_type'], name='app_provide_provide_377757_idx')],
            },
        ),
    ]
