# Generated by Django 6.0.3 on 2026-04-07 08:38

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AddField(
            model_name='provider',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Реферальная ссылка на регистрацию у провайдера для подключённых обменников.', verbose_name='Партнёрская ссылка'),
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, help_text='Свободный комментарий или заметка для администратора.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='code',
            field=models.SlugField(help_text='Стабильный системный код провайдера, например: binance, bybit, okx.', max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Глобальный административный флаг. Разрешён ли провайдер к использованию в системе вообще.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Технические или дополнительные данные о провайдере в JSON-формате.', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Человекочитаемое название провайдера.', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Чем меньше число, тем выше приоритет провайдера.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('otc', 'OTC'), ('wallet', 'Wallet'), ('blockchain', 'Blockchain'), ('internal', 'Internal'), ('other', 'Other')], db_index=True, default='exchange', max_length=32, verbose_name='Тип провайдера'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['provider_type'], name='prov_type_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active', 'priority'], name='prov_active_prio_idx'),
        ),
        migrations.AlterModelTable(
            name='provider',
            table='providers_provider',
        ),
    ]
