# Generated by Django 6.0.3 on 2026-04-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0002_alter_provider_options_provider_affiliate_url_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='provider',
            table=None,
        ),
    ]
