# Generated by Django 6.0.3 on 2026-04-07 09:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0003_alter_provider_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Человекочитаемое название набора доступов.', max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Разрешено ли использовать этот набор доступов.', verbose_name='Активен')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='Чем меньше число, тем выше приоритет этого набора доступов.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Приоритет')),
                ('description', models.TextField(blank=True, help_text='Свободная заметка администратора.', verbose_name='Описание')),
                ('api_key', models.TextField(blank=True, help_text='API Key провайдера. Хранится как текст, так как может быть очень длинным.', verbose_name='API Key')),
                ('api_secret', models.TextField(blank=True, help_text='API Secret провайдера.', verbose_name='API Secret')),
                ('api_passphrase', models.TextField(blank=True, help_text='Дополнительная passphrase, если требуется провайдером.', verbose_name='API Passphrase')),
                ('broker_key', models.TextField(blank=True, help_text='Broker key, если используется провайдером.', verbose_name='Broker Key')),
                ('trade_password', models.TextField(blank=True, help_text='Торговый пароль, если используется провайдером.', verbose_name='Trade Password')),
                ('is_ip_whitelist_enabled', models.BooleanField(default=False, help_text='Ограничен ли доступ к этому набору ключей по IP.', verbose_name='Включён whitelist IP')),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list, help_text='Список разрешённых IP или CIDR, например: ["1.2.3.4/32", "5.6.7.0/24"].', verbose_name='Разрешённые IP/CIDR')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='app_providers.provider', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Доступ к провайдеру',
                'verbose_name_plural': 'Доступы к провайдерам',
                'ordering': ('provider', 'priority', 'name'),
                'indexes': [models.Index(fields=['provider', 'is_active'], name='provcred_prov_active_idx'), models.Index(fields=['provider', 'priority'], name='provcred_prov_prio_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'name'), name='uniq_providercredential_provider_name')],
            },
        ),
    ]
