# Generated by Django 6.0.3 on 2026-04-07 10:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0004_providercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercredential',
            name='fees_updated_at',
            field=models.DateTimeField(blank=True, help_text='Когда комиссии были последний раз обновлены вручную или автоматически.', null=True, verbose_name='Дата обновления комиссий'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='futures_maker_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.001'), help_text='Торговая комиссия maker на фьючерсах. Хранится в виде доли. Пример: 0.001 = 0.1%, 0 = 0%, -0.0001 = -0.01%.', max_digits=10, verbose_name='Futures maker fee'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='futures_taker_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.001'), help_text='Торговая комиссия taker на фьючерсах. Хранится в виде доли. Пример: 0.001 = 0.1%, 0 = 0%, -0.0001 = -0.01%.', max_digits=10, verbose_name='Futures taker fee'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='spot_maker_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.001'), help_text='Торговая комиссия maker на споте. Хранится в виде доли. Пример: 0.001 = 0.1%, 0 = 0%, -0.0001 = -0.01%.', max_digits=10, verbose_name='Spot maker fee'),
        ),
        migrations.AddField(
            model_name='providercredential',
            name='spot_taker_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.001'), help_text='Торговая комиссия taker на споте. Хранится в виде доли. Пример: 0.001 = 0.1%, 0 = 0%, -0.0001 = -0.01%.', max_digits=10, verbose_name='Spot taker fee'),
        ),
    ]
