# Generated by Django 6.0.3 on 2026-04-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0005_providercredential_fees_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providercapability',
            options={'verbose_name': 'Возможности провайдера', 'verbose_name_plural': 'Возможности провайдеров'},
        ),
        migrations.RemoveField(
            model_name='providercapability',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='providercapability',
            name='supports_asset_metadata',
        ),
        migrations.RemoveField(
            model_name='providercapability',
            name='supports_market_snapshot',
        ),
        migrations.RemoveField(
            model_name='providercapability',
            name='supports_network_metadata',
        ),
        migrations.RemoveField(
            model_name='providercapability',
            name='supports_rest',
        ),
        migrations.RemoveField(
            model_name='providercapability',
            name='supports_ws',
        ),
        migrations.AddField(
            model_name='providercapability',
            name='description',
            field=models.TextField(blank=True, help_text='Свободный комментарий или заметка для администратора.', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='providercapability',
            name='supports_deposit',
            field=models.BooleanField(default=False, help_text='Можно ли через этого провайдера принимать средства.', verbose_name='Поддерживает ввод средств'),
        ),
        migrations.AddField(
            model_name='providercapability',
            name='supports_futures_trading',
            field=models.BooleanField(default=False, help_text='Можно ли использовать провайдера для торговли фьючерсами.', verbose_name='Поддерживает фьючерсы'),
        ),
        migrations.AddField(
            model_name='providercapability',
            name='supports_price_feed',
            field=models.BooleanField(default=True, help_text='Может ли провайдер использоваться как источник цен.', verbose_name='Поддерживает трансляцию цен'),
        ),
        migrations.AddField(
            model_name='providercapability',
            name='supports_spot_trading',
            field=models.BooleanField(default=False, help_text='Можно ли использовать провайдера для спотовой торговли.', verbose_name='Поддерживает спот'),
        ),
        migrations.AddField(
            model_name='providercapability',
            name='supports_trade_execution',
            field=models.BooleanField(default=False, help_text='Можно ли через этого провайдера реально исполнять обмены или торговые операции.', verbose_name='Поддерживает исполнение сделок'),
        ),
        migrations.AddField(
            model_name='providercapability',
            name='supports_withdraw',
            field=models.BooleanField(default=False, help_text='Можно ли через этого провайдера выводить средства.', verbose_name='Поддерживает вывод средств'),
        ),
    ]
