# Generated by Django 6.0.3 on 2026-04-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0006_alter_providercapability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercapability',
            name='supports_deposit',
            field=models.BooleanField(default=False, help_text='Через этого провайдера можно принимать средства. Например: биржа, обменник, кошелёк, нода или другой платёжный/расчётный контур, на который можно завести актив.', verbose_name='Поддерживает ввод средств'),
        ),
        migrations.AlterField(
            model_name='providercapability',
            name='supports_futures_trading',
            field=models.BooleanField(default=False, help_text='Провайдер поддерживает торговлю фьючерсами. Если поле включено, то исполнение сделок тоже должно быть включено.', verbose_name='Поддерживает фьючерсы'),
        ),
        migrations.AlterField(
            model_name='providercapability',
            name='supports_price_feed',
            field=models.BooleanField(default=True, help_text='Провайдер может использоваться как источник цен. Это относится к биржам, обменникам, агрегаторам, ЦБ РФ и другим источникам котировок. Если провайдер нужен только для движения средств без получения цен, это поле можно выключить.', verbose_name='Поддерживает трансляцию цен'),
        ),
        migrations.AlterField(
            model_name='providercapability',
            name='supports_spot_trading',
            field=models.BooleanField(default=False, help_text='Провайдер поддерживает спотовую торговлю или спотовый обмен. Если поле включено, то исполнение сделок тоже должно быть включено.', verbose_name='Поддерживает спот'),
        ),
        migrations.AlterField(
            model_name='providercapability',
            name='supports_trade_execution',
            field=models.BooleanField(default=False, help_text='Провайдер умеет не только принимать или отправлять средства, но и выполнять сам обмен или торговую операцию. Это относится к биржам, обменникам, OTC и другим execution-площадкам. Для нод, кошельков и прочих transfer-only провайдеров это поле обычно выключено.', verbose_name='Поддерживает исполнение сделок'),
        ),
        migrations.AlterField(
            model_name='providercapability',
            name='supports_withdraw',
            field=models.BooleanField(default=False, help_text='Через этого провайдера можно отправлять средства наружу. Например: вывод с биржи, отправка с кошелька или перевод через собственную ноду.', verbose_name='Поддерживает вывод средств'),
        ),
    ]
