# Generated by Django 6.0.3 on 2026-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0007_alter_providercapability_supports_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercapability',
            name='supports_address_generation',
            field=models.BooleanField(default=False, help_text='Можно ли автоматически получать адрес для пополнения через этого провайдера. Это поле относится именно к генерации или выдаче депозитного адреса, а не просто к факту, что провайдер умеет принимать средства.', verbose_name='Поддерживает генерацию адресов'),
        ),
    ]
