# Generated by Django 6.0.3 on 2026-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0008_providercapability_supports_address_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercapability',
            name='supports_trade_execution',
            field=models.BooleanField(default=False, help_text='Провайдер умеет не только принимать или отправлять средства, но и выполнять сам обмен при этом комиссии включены в курс. Типичная модель работы OTC. Комиссия за обмен здесь не добавляется.', verbose_name='Поддерживает исполнение сделок'),
        ),
    ]
