# Generated by Django 6.0.3 on 2026-04-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0009_alter_providercapability_supports_trade_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_calculated_at', models.DateTimeField(blank=True, help_text='Когда статистика по провайдеру была рассчитана в последний раз.', null=True, verbose_name='Дата последнего расчёта')),
                ('pairs_total', models.PositiveIntegerField(default=0, help_text='Общее количество найденных торговых пар у провайдера.', verbose_name='Всего торговых пар')),
                ('quote_assets_total', models.PositiveIntegerField(default=0, help_text='Сколько разных quote-активов найдено у провайдера.', verbose_name='Всего quote-активов')),
                ('stablecoins_total', models.PositiveIntegerField(default=0, help_text='Сколько quote-активов из списка стейблкоинов оказалось у провайдера.', verbose_name='Всего активных стейблкоинов')),
                ('quote_asset_counts', models.JSONField(blank=True, default=dict, help_text='JSON-словарь вида {"USDT": 300, "USDC": 40}. Показывает, сколько торговых пар найдено против каждого quote-актива.', verbose_name='Количество пар по quote-активам')),
                ('stablecoin_pair_counts', models.JSONField(blank=True, default=dict, help_text='JSON-словарь вида {"USDT": 300, "USDC": 40}. Содержит только те quote-активы, которые попали в список стейблкоинов.', verbose_name='Количество пар по стейблкоинам')),
                ('active_stablecoins', models.JSONField(blank=True, default=list, help_text='JSON-список вида ["USDT", "USDC"]. Стейблкоины отсортированы по убыванию количества торговых пар.', verbose_name='Активные стейблкоины')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app_providers.provider', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Статистика провайдера',
                'verbose_name_plural': 'Статистика провайдеров',
            },
        ),
    ]
