# Generated by Django 6.0.3 on 2026-04-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0010_providerstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerstatus',
            options={'verbose_name': 'Статус провайдера', 'verbose_name_plural': 'Статусы провайдеров'},
        ),
        migrations.RemoveField(
            model_name='providerstatus',
            name='health_score',
        ),
        migrations.AddField(
            model_name='providerstatus',
            name='address_generation_enabled',
            field=models.BooleanField(default=False, help_text='Можно ли сейчас получать адреса для пополнения через этого провайдера.', verbose_name='Генерация адресов доступна'),
        ),
        migrations.AddField(
            model_name='providerstatus',
            name='deposit_enabled',
            field=models.BooleanField(default=False, help_text='Можно ли сейчас принимать средства через этого провайдера.', verbose_name='Ввод средств доступен'),
        ),
        migrations.AddField(
            model_name='providerstatus',
            name='futures_trading_enabled',
            field=models.BooleanField(default=False, help_text='Можно ли сейчас использовать торговлю фьючерсами через этого провайдера.', verbose_name='Фьючерсы доступны'),
        ),
        migrations.AddField(
            model_name='providerstatus',
            name='price_feed_enabled',
            field=models.BooleanField(default=True, help_text='Можно ли сейчас получать цены от провайдера.', verbose_name='Трансляция цен доступна'),
        ),
        migrations.AddField(
            model_name='providerstatus',
            name='spot_trading_enabled',
            field=models.BooleanField(default=False, help_text='Можно ли сейчас использовать спотовую торговлю через этого провайдера.', verbose_name='Спот доступен'),
        ),
        migrations.AddField(
            model_name='providerstatus',
            name='trade_execution_enabled',
            field=models.BooleanField(default=False, help_text='Можно ли сейчас выполнять обмены или торговые операции через этого провайдера.', verbose_name='Исполнение сделок доступно'),
        ),
        migrations.AddField(
            model_name='providerstatus',
            name='withdraw_enabled',
            field=models.BooleanField(default=False, help_text='Можно ли сейчас отправлять средства через этого провайдера.', verbose_name='Вывод средств доступен'),
        ),
        migrations.AlterField(
            model_name='providerstatus',
            name='last_error_at',
            field=models.DateTimeField(blank=True, help_text='Когда в последний раз была зафиксирована ошибка при работе с провайдером.', null=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='providerstatus',
            name='last_error_message',
            field=models.TextField(blank=True, help_text='Последняя зафиксированная ошибка или причина деградации.', verbose_name='Текст последней ошибки'),
        ),
        migrations.AlterField(
            model_name='providerstatus',
            name='last_success_at',
            field=models.DateTimeField(blank=True, help_text='Когда в последний раз взаимодействие с провайдером прошло успешно.', null=True, verbose_name='Последний успешный доступ'),
        ),
        migrations.AlterField(
            model_name='providerstatus',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app_providers.provider', verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='providerstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('degraded', 'Degraded'), ('maintenance', 'Maintenance'), ('disabled', 'Disabled'), ('error', 'Error')], db_index=True, default='active', help_text='Агрегированное текущее состояние провайдера. Используется как общий operational-статус.', max_length=32, verbose_name='Общий статус'),
        ),
    ]
