# Generated by Django 6.0.3 on 2026-04-07 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_providers', '0011_alter_providerstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_calculated_at', models.DateTimeField(blank=True, help_text='Когда статистика по провайдеру была рассчитана в последний раз.', null=True, verbose_name='Дата последнего расчёта')),
                ('pairs_total', models.PositiveIntegerField(default=0, help_text='Общее количество найденных торговых пар у провайдера.', verbose_name='Всего торговых пар')),
                ('quote_assets_total', models.PositiveIntegerField(default=0, help_text='Сколько разных quote-активов найдено у провайдера.', verbose_name='Всего quote-активов')),
                ('stablecoins_total', models.PositiveIntegerField(default=0, help_text='Сколько quote-активов из списка стейблкоинов оказалось у провайдера.', verbose_name='Всего активных стейблкоинов')),
                ('quote_asset_counts', models.JSONField(blank=True, default=dict, help_text='JSON-словарь вида {"USDT": 300, "USDC": 40}. Показывает, сколько торговых пар найдено против каждого quote-актива.', verbose_name='Количество пар по quote-активам')),
                ('stablecoin_pair_counts', models.JSONField(blank=True, default=dict, help_text='JSON-словарь вида {"USDT": 300, "USDC": 40}. Содержит только те quote-активы, которые попали в список стейблкоинов.', verbose_name='Количество пар по стейблкоинам')),
                ('active_stablecoins', models.JSONField(blank=True, default=list, help_text='JSON-список вида ["USDT", "USDC"]. Стейблкоины отсортированы по убыванию количества торговых пар.', verbose_name='Активные стейблкоины')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистики',
            },
        ),
        migrations.RemoveIndex(
            model_name='providerendpoint',
            name='app_provide_provide_377757_idx',
        ),
        migrations.AlterModelOptions(
            name='providerstatus',
            options={'verbose_name': 'Состояние', 'verbose_name_plural': 'Состоянии'},
        ),
        migrations.AddField(
            model_name='providermetrics',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='app_providers.provider', verbose_name='Провайдер'),
        ),
        migrations.RemoveField(
            model_name='providerendpoint',
            name='provider',
        ),
        migrations.DeleteModel(
            name='ProviderStats',
        ),
        migrations.DeleteModel(
            name='ProviderEndpoint',
        ),
    ]
