# Generated by Django 6.0.3 on 2026-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('stablecoin_codes', models.TextField(blank=True, help_text='Список кодов стейблкоинов. Можно вводить через запятую или с новой строки. При сохранении список будет очищен от дублей, отсортирован по алфавиту и сохранён по одному значению на строку. Регистр не изменяется.', verbose_name='Коды стейблкоинов')),
                ('fiat_currency_codes', models.TextField(blank=True, help_text='Список кодов фиатных валют. Можно вводить через запятую или с новой строки. При сохранении список будет очищен от дублей, отсортирован по алфавиту и сохранён по одному значению на строку. Регистр не изменяется.', verbose_name='Коды фиатных валют')),
                ('memo_tag_network_codes', models.TextField(blank=True, help_text='Список кодов сетей, где для перевода требуется MEMO, TAG, Destination Tag или аналогичное поле. Можно вводить через запятую или с новой строки. При сохранении список будет очищен от дублей, отсортирован по алфавиту и сохранён по одному значению на строку. Регистр не изменяется.', verbose_name='Коды сетей с MEMO/TAG')),
                ('description', models.TextField(blank=True, help_text='Свободный комментарий для администратора.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Глобальные настройки платформы',
                'verbose_name_plural': 'Глобальные настройки платформы',
            },
        ),
    ]
