# Generated by Django 6.0.3 on 2026-04-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='description',
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='fiat_currency_codes',
            field=models.TextField(blank=True, default='AED\nAFN\nALL\nAMD\nANG\nAOA\nARS\nAUD\nAWG\nAZN\nBAM\nBBD\nBDT\nBGN\nBHD\nBIF\nBMD\nBND\nBOB\nBRL\nBSD\nBTN\nBWP\nBYN\nBZD\nCAD\nCDF\nCHF\nCLP\nCNY\nCOP\nCRC\nCUP\nCVE\nCZK\nDJF\nDKK\nDOP\nDZD\nEGP\nERN\nETB\nEUR\nFJD\nFKP\nGBP\nGEL\nGHS\nGIP\nGMD\nGNF\nGTQ\nGYD\nHKD\nHNL\nHTG\nHUF\nIDR\nILS\nINR\nIQD\nIRR\nISK\nJMD\nJOD\nJPY\nKES\nKGS\nKHR\nKMF\nKPW\nKRW\nKWD\nKYD\nKZT\nLAK\nLBP\nLKR\nLRD\nLSL\nLYD\nMAD\nMDL\nMGA\nMKD\nMMK\nMNT\nMOP\nMRU\nMUR\nMVR\nMWK\nMXN\nMYR\nMZN\nNAD\nNGN\nNIO\nNOK\nNPR\nNZD\nOMR\nPAB\nPEN\nPGK\nPHP\nPKR\nPLN\nPYG\nQAR\nRON\nRSD\nRUB\nRWF\nSAR\nSBD\nSCR\nSDG\nSEK\nSGD\nSHP\nSLE\nSOS\nSRD\nSSP\nSTN\nSYP\nSZL\nTHB\nTJS\nTMT\nTND\nTOP\nTRY\nTTD\nTWD\nTZS\nUAH\nUAHG\nUGX\nUSD\nUYU\nUZS\nVED\nVES\nVND\nVUV\nWST\nXAF\nXAUT\nXCD\nXOF\nXPF\nYER\nZAR\nZMW\nZWG', help_text='Список кодов фиатных валют. Можно вводить через запятую или с новой строки. При сохранении список будет очищен от дублей, отсортирован по алфавиту и сохранён по одному значению на строку. Регистр не изменяется.', verbose_name='Коды фиатных валют'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='memo_tag_network_codes',
            field=models.TextField(blank=True, default='ATOM\nBNB\nEOS\nHBAR\nKAVA\nLUNA\nLUNC\nNOT\nOSMO\nTON\nXEM\nXLM\nXRP', help_text='Список кодов сетей, где для перевода требуется MEMO, TAG, Destination Tag или аналогичное поле. Можно вводить через запятую или с новой строки. При сохранении список будет очищен от дублей, отсортирован по алфавиту и сохранён по одному значению на строку. Регистр не изменяется.', verbose_name='Коды сетей с MEMO/TAG'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='stablecoin_codes',
            field=models.TextField(blank=True, default='AEUR\nAUDD\nBOLD\nBRZ\nCADC\nDAI\nDECL\nDJED\nDOLA\nEURA\nEURC\nEURI\nEUROe\nEURR\nEURS\nEURT\nEURe\nFDUSD\nFRAX\nGBPT\nGBPe\nGHO\nGRAI\nGUSD\nGYEN\nHAY\nHCHF\nJPYC\nLUSD\nMIM\nMXNT\nPAR\nPYUSD\nQCAD\nRLUSD\nTAUD\nTRYB\nTUSD\nUSD0\nUSD1\nUSDA\nUSDC\nUSDD\nUSDH\nUSDK\nUSDM\nUSDP\nUSDR\nUSDS\nUSDT\nUSDV\nUSDe\nUSK\nUSX\nVAI\nVCHF\nXCHF\nXIDR\nXSGD\nZARP\nagEUR\nalUSD\ncEUR\ncrvUSD\neUSD\nfrxUSD\njEUR\nsUSD', help_text='Список кодов стейблкоинов. Можно вводить через запятую или с новой строки. При сохранении список будет очищен от дублей, отсортирован по алфавиту и сохранён по одному значению на строку. Регистр не изменяется.', verbose_name='Коды стейблкоинов'),
        ),
    ]
