# Generated by Django 6.0.3 on 2026-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_remove_platformsettings_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='description',
            field=models.TextField(blank=True, help_text='Свободный комментарий для администратора.', verbose_name='Описание'),
        ),
    ]
