# Generated by Django 6.0.3 on 2026-04-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_platformsettings_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='description',
        ),
    ]
