# Generated by Django 6.0.3 on 2026-04-06 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list, verbose_name='Разрешённые IP/CIDR')),
                ('is_ip_whitelist_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Whitelist включён')),
                ('policy_notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_policy', to='app_tenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant access policy',
                'verbose_name_plural': 'Tenant access policies',
            },
        ),
        migrations.CreateModel(
            name='TenantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('grace', 'Grace')], db_index=True, default='active', max_length=32, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_record', to='app_tenancy.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant status',
                'verbose_name_plural': 'Tenant statuses',
            },
        ),
    ]
